- name: Copy CONGA vhosts.
  include_role:
    name: wcm-io-devops.conga-files
  vars:
    conga_files_base_path: "{{ apache_config_path }}"
    conga_files_handlers: [ restart apache ]
    conga_files_files: "{{ conga_files_paths | select('match', 'vhosts.d/') | list }}"

- name: Include vhosts from vhosts.d.
  lineinfile:
    dest: "{{ apache_config_path }}/conf.d/vhosts.conf"
    line: 'IncludeOptional vhosts.d/*.conf'
    create: yes
  notify:
    - restart apache