- name: Copy CONGA vhosts.
  include_role:
    name: wcm_io_devops.conga_files
  vars:
    conga_files_base_path: "{{ apache_config_path }}/sites-available"
    conga_files_handlers: [ restart apache ]
    conga_files_files: "{{ conga_files_paths | select('match', 'vhosts.d/') | list }}"
    conga_files_directories: []
    conga_files_strip: 'vhosts.d/'

- name: Enable CONGA sites.
  command: "a2ensite {{ item | basename }}"
  args:
    creates: "{{ apache_config_path }}/sites-enabled/{{ item | basename }}"
  with_items: "{{ conga_files_paths | select('match', 'vhosts.d/.*') | list }}"
  notify:
    - restart apache