- name: Get installed version of Apache.
  command: "httpd -v"
  register: _apache_version
  changed_when: true

- name: Include httpd module setup.
  include_tasks: "enable_modules.yml"

# Shims for Debian compatibility
- name: Create /etc/ssl/private link for SSL key files.
  file:
    src: /etc/pki/tls/private
    dest: /etc/ssl/private
    state: link
  when: "'ssl' in conga_variants"

- name: Set APACHE_LOG_DIR variable.
  lineinfile:
    dest: "{{ _apache_config_path }}/conf.d/00-envvars.conf"
    line: 'Define APACHE_LOG_DIR /var/log/httpd'
    create: yes
  notify:
    - restart apache

# copy all conf files from conf.d to conf.d on redhat
- name: Copy conf.d CONGA files
  include_role:
    name: wcm_io_devops.conga_files
  vars:
    conga_files_base_path: "{{ _apache_config_path }}"
    conga_files_handlers: [ restart apache ]
    conga_files_files: "{{ conga_files_paths | select('match', '^conf.d/.*') | list }}"
    conga_files_directories: "{{ conga_directories | select('match', '^conf.d/.*') | list }}"
