- name: Get installed version of Apache.
  command: "apachectl -v"
  register: _apache_version
  changed_when: true

- name: Include httpd module setup.
  include_tasks: "enable_modules.yml"

# Copy conf files from conf.d to conf-available
- name: Copy conf.d CONGA files to conf-available.
  include_role:
    name: wcm_io_devops.conga_files
  vars:
    conga_files_base_path: "{{ _apache_config_path }}/conf-available"
    conga_files_strip: "conf.d/"
    conga_files_handlers: [ restart apache ]
    conga_files_files: "{{ conga_files_paths | select('match', '^conf.d/.*') | list }}"
    conga_files_directories: []

# enable all configuration files that were copied to conf-available
- name: Enable CONGA Apache configurations.
  command: a2enconf {{ item | basename }}
  args:
    creates: "{{ _apache_config_path }}/conf-enabled/{{ item | basename }}"
  with_items: "{{ conga_files_paths | select('match', '^conf.d/.*') | list }}"
  notify:
    - restart apache
